CREATE DATABASE IF NOT EXISTS Assignment1DB;

USE Assignment1DB;

CREATE TABLE IF NOT EXISTS T1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS T2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255)
);

ALTER TABLE T1 PARTITION BY RANGE (id) (
    PARTITION P1 VALUES LESS THAN (50),
    PARTITION P2 VALUES LESS THAN (150),
    PARTITION P3 VALUES LESS THAN (200),
    PARTITION P4 VALUES LESS THAN MAXVALUE
);

ALTER TABLE T2 PARTITION BY RANGE (id) (
    PARTITION P1 VALUES LESS THAN (50),
    PARTITION P2 VALUES LESS THAN (150),
    PARTITION P3 VALUES LESS THAN (200),
    PARTITION P4 VALUES LESS THAN MAXVALUE
);
